# Generated by Django 3.0.3 on 2020-08-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=32)),
                ('size', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('thumbnail_path', models.CharField(max_length=500, null=True)),
                ('thumbnail_name', models.CharField(max_length=200, null=True)),
                ('exif_exposure_time', models.CharField(max_length=100, null=True)),
                ('exif_fnumber', models.CharField(max_length=100, null=True)),
                ('exif_datetime', models.DateTimeField(null=True)),
                ('exif_gpslatitude', models.CharField(max_length=100, null=True)),
                ('exif_gpslongitude', models.CharField(max_length=100, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
