# Generated by Django 3.0.3 on 2020-08-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
