# Generated by Django 3.0.3 on 2020-08-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20200805_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_name',
        ),
    ]
